openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
  description: Views and manages your Google Analytics data.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics
  version: v2.4
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_analytics_64dp.png
  x-origin:
  - converter:
      url: https://github.com/lucybot/api-spec-converter
      version: 2.7.31
    format: google
    url: https://www.googleapis.com/discovery/v1/apis/analytics/v2.4/rest
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: analytics
servers:
- url: https://www.googleapis.com/analytics/v2.4
tags:
- name: data
- name: management
paths:
  /data:
    get:
      description: Returns Analytics report data for a view (profile).
      operationId: analytics.data.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - data
      x-accepts:
      - application/json
  /management/accounts:
    get:
      description: Lists all accounts to which the user has access.
      operationId: analytics.management.accounts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
      x-accepts:
      - application/json
  /management/accounts/{accountId}/webproperties:
    get:
      description: Lists web properties to which the user has access.
      operationId: analytics.management.webproperties.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
      x-accepts:
      - application/json
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles:
    get:
      description: Lists views (profiles) to which the user has access.
      operationId: analytics.management.profiles.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
      x-accepts:
      - application/json
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals:
    get:
      description: Lists goals to which the user has access.
      operationId: analytics.management.goals.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
      x-accepts:
      - application/json
  /management/segments:
    get:
      description: Lists advanced segments to which the user has access.
      operationId: analytics.management.segments.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
        Oauth2c:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
      x-accepts:
      - application/json
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google
              Analytics data
            https://www.googleapis.com/auth/analytics.readonly: View your Google Analytics
              data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics: View and manage your Google
              Analytics data
            https://www.googleapis.com/auth/analytics.readonly: View your Google Analytics
              data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2

