# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HlsDirectoryStructure(str, Enum):
    """
    Indicates whether segments should be placed in subdirectories.
    """

    """
    allowed enum values
    """
    SINGLE_DIRECTORY = 'SINGLE_DIRECTORY'
    SUBDIRECTORY_PER_STREAM = 'SUBDIRECTORY_PER_STREAM'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HlsDirectoryStructure from a JSON string"""
        return cls(json.loads(json_str))


