# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InputPsiControl(str, Enum):
    """
    Set PSI control (InputPsiControl) for transport stream inputs to specify which data the demux process to scans. * Ignore PSI - Scan all PIDs for audio and video. * Use PSI - Scan only PSI data.
    """

    """
    allowed enum values
    """
    IGNORE_PSI = 'IGNORE_PSI'
    USE_PSI = 'USE_PSI'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InputPsiControl from a JSON string"""
        return cls(json.loads(json_str))


