# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SccDestinationFramerate(str, Enum):
    """
    Set Framerate (SccDestinationFramerate) to make sure that the captions and the video are synchronized in the output. Specify a frame rate that matches the frame rate of the associated video. If the video frame rate is 29.97, choose 29.97 dropframe (FRAMERATE_29_97_DROPFRAME) only if the video has video_insertion=true and drop_frame_timecode=true; otherwise, choose 29.97 non-dropframe (FRAMERATE_29_97_NON_DROPFRAME).
    """

    """
    allowed enum values
    """
    FRAMERATE_23_97 = 'FRAMERATE_23_97'
    FRAMERATE_24 = 'FRAMERATE_24'
    FRAMERATE_25 = 'FRAMERATE_25'
    FRAMERATE_29_97_DROPFRAME = 'FRAMERATE_29_97_DROPFRAME'
    FRAMERATE_29_97_NON_DROPFRAME = 'FRAMERATE_29_97_NON_DROPFRAME'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SccDestinationFramerate from a JSON string"""
        return cls(json.loads(json_str))


