# coding: utf-8

"""
    Discovery API

    The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.date_time_zone import DateTimeZone

class TestDateTimeZone(unittest.TestCase):
    """DateTimeZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateTimeZone:
        """Test DateTimeZone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateTimeZone`
        """
        model = DateTimeZone()
        if include_optional:
            return DateTimeZone(
                fixed = True,
                id = ''
            )
        else:
            return DateTimeZone(
        )
        """

    def testDateTimeZone(self):
        """Test DateTimeZone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
