/*
 * Amazon Personalize
 * Amazon Personalize is a machine learning service that makes it easy to add individualized recommendations to customers.
 *
 * The version of the OpenAPI document: 2018-05-22
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListBatchInferenceJobsResponse
 */
public class ListBatchInferenceJobsResponseTest {
    private final ListBatchInferenceJobsResponse model = new ListBatchInferenceJobsResponse();

    /**
     * Model tests for ListBatchInferenceJobsResponse
     */
    @Test
    public void testListBatchInferenceJobsResponse() {
        // TODO: test ListBatchInferenceJobsResponse
    }

    /**
     * Test the property 'batchInferenceJobs'
     */
    @Test
    public void batchInferenceJobsTest() {
        // TODO: test batchInferenceJobs
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

}
