# coding: utf-8

"""
    Legal Entity Management API

    The Legal Entity Management API enables you to manage legal entities that contain information required for verification.  ## Authentication To connect to the Legal Entity Management API, you must use the basic authentication credentials of your web service user. If you don't have one, contact the [Adyen Support Team](https://www.adyen.help/hc/en-us/requests/new). Use the web service user credentials to authenticate your request, for example:  ``` curl -U \"ws_123456@Scope.BalancePlatform_YourBalancePlatform\":\"YourWsPassword\" \\ -H \"Content-Type: application/json\" \\ ... ``` Note that when going live, you need to generate new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).  ## Versioning The Legal Entity Management API supports versioning of its endpoints through a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.  For example: ``` https://kyc-test.adyen.com/lem/v3/legalEntities ``` ## Going live When going live, your Adyen contact will provide your API credential for the live environment. You can then use the username and password to send requests to `https://kyc-live.adyen.com/lem/v3`.  

    The version of the OpenAPI document: 3
    Contact: developer-experience@adyen.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.legal_entities_api import LegalEntitiesApi


class TestLegalEntitiesApi(unittest.TestCase):
    """LegalEntitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LegalEntitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_legal_entities_id(self) -> None:
        """Test case for get_legal_entities_id

        Get a legal entity
        """
        pass

    def test_get_legal_entities_id_business_lines(self) -> None:
        """Test case for get_legal_entities_id_business_lines

        Get all business lines under a legal entity
        """
        pass

    def test_patch_legal_entities_id(self) -> None:
        """Test case for patch_legal_entities_id

        Update a legal entity
        """
        pass

    def test_post_legal_entities(self) -> None:
        """Test case for post_legal_entities

        Create a legal entity
        """
        pass

    def test_post_legal_entities_id_check_verification_errors(self) -> None:
        """Test case for post_legal_entities_id_check_verification_errors

        Check a legal entity's verification errors
        """
        pass


if __name__ == '__main__':
    unittest.main()
