# coding: utf-8

"""
    Amazon Pinpoint

    Doc Engage API - Amazon Pinpoint API

    The version of the OpenAPI document: 2016-12-01
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.in_app_message_content_secondary_btn import InAppMessageContentSecondaryBtn

class TestInAppMessageContentSecondaryBtn(unittest.TestCase):
    """InAppMessageContentSecondaryBtn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InAppMessageContentSecondaryBtn:
        """Test InAppMessageContentSecondaryBtn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InAppMessageContentSecondaryBtn`
        """
        model = InAppMessageContentSecondaryBtn()
        if include_optional:
            return InAppMessageContentSecondaryBtn(
                android = None,
                default_config = None,
                ios = None,
                web = None
            )
        else:
            return InAppMessageContentSecondaryBtn(
        )
        """

    def testInAppMessageContentSecondaryBtn(self):
        """Test InAppMessageContentSecondaryBtn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
