# coding: utf-8

"""
    Amazon Pinpoint

    Doc Engage API - Amazon Pinpoint API

    The version of the OpenAPI document: 2016-12-01
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.segment_type import SegmentType

class TestSegmentType(unittest.TestCase):
    """SegmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSegmentType(self):
        """Test SegmentType"""
        # inst = SegmentType()

if __name__ == '__main__':
    unittest.main()
