# coding: utf-8

"""
    Amazon Pinpoint

    Doc Engage API - Amazon Pinpoint API

    The version of the OpenAPI document: 2016-12-01
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.write_journey_request import WriteJourneyRequest

class TestWriteJourneyRequest(unittest.TestCase):
    """WriteJourneyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WriteJourneyRequest:
        """Test WriteJourneyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WriteJourneyRequest`
        """
        model = WriteJourneyRequest()
        if include_optional:
            return WriteJourneyRequest(
                activities = None,
                creation_date = None,
                last_modified_date = None,
                limits = None,
                local_time = None,
                name = None,
                quiet_time = None,
                refresh_frequency = None,
                schedule = None,
                start_activity = None,
                start_condition = None,
                state = None,
                wait_for_quiet_time = None,
                refresh_on_segment_update = None,
                journey_channel_settings = None,
                sending_schedule = None,
                open_hours = None,
                closed_days = None
            )
        else:
            return WriteJourneyRequest(
                name = None,
        )
        """

    def testWriteJourneyRequest(self):
        """Test WriteJourneyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
