# coding: utf-8

"""
    Amazon Pinpoint

    Doc Engage API - Amazon Pinpoint API

    The version of the OpenAPI document: 2016-12-01
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.endpoint_location import EndpointLocation

class TestEndpointLocation(unittest.TestCase):
    """EndpointLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndpointLocation:
        """Test EndpointLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EndpointLocation`
        """
        model = EndpointLocation()
        if include_optional:
            return EndpointLocation(
                city = None,
                country = None,
                latitude = None,
                longitude = None,
                postal_code = None,
                region = None
            )
        else:
            return EndpointLocation(
        )
        """

    def testEndpointLocation(self):
        """Test EndpointLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
