# coding: utf-8

"""
    Twilio - Taskrouter

    This is the public Twilio REST API.

    The version of the OpenAPI document: 1.42.0
    Contact: support@twilio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.worker_reservation_enum_status import WorkerReservationEnumStatus

class TestWorkerReservationEnumStatus(unittest.TestCase):
    """WorkerReservationEnumStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkerReservationEnumStatus(self):
        """Test WorkerReservationEnumStatus"""
        # inst = WorkerReservationEnumStatus()

if __name__ == '__main__':
    unittest.main()
