# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProresCodecProfile(str, Enum):
    """
    Use Profile (ProResCodecProfile) to specify the type of Apple ProRes codec to use for this output.
    """

    """
    allowed enum values
    """
    APPLE_PRORES_422 = 'APPLE_PRORES_422'
    APPLE_PRORES_422_HQ = 'APPLE_PRORES_422_HQ'
    APPLE_PRORES_422_LT = 'APPLE_PRORES_422_LT'
    APPLE_PRORES_422_PROXY = 'APPLE_PRORES_422_PROXY'
    APPLE_PRORES_4444 = 'APPLE_PRORES_4444'
    APPLE_PRORES_4444_XQ = 'APPLE_PRORES_4444_XQ'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProresCodecProfile from a JSON string"""
        return cls(json.loads(json_str))


