# coding: utf-8

"""
    Discovery API

    The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.display_setting_extension import DisplaySettingExtension

class TestDisplaySettingExtension(unittest.TestCase):
    """DisplaySettingExtension unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DisplaySettingExtension:
        """Test DisplaySettingExtension
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DisplaySettingExtension`
        """
        model = DisplaySettingExtension()
        if include_optional:
            return DisplaySettingExtension(
                soft_landing = True
            )
        else:
            return DisplaySettingExtension(
        )
        """

    def testDisplaySettingExtension(self):
        """Test DisplaySettingExtension"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
