# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CheckAnnotation(BaseModel):
    """
    Check Annotation
    """ # noqa: E501
    annotation_level: Optional[StrictStr]
    blob_href: StrictStr
    end_column: Optional[StrictInt]
    end_line: StrictInt
    message: Optional[StrictStr]
    path: StrictStr
    raw_details: Optional[StrictStr]
    start_column: Optional[StrictInt]
    start_line: StrictInt
    title: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["annotation_level", "blob_href", "end_column", "end_line", "message", "path", "raw_details", "start_column", "start_line", "title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckAnnotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if annotation_level (nullable) is None
        # and model_fields_set contains the field
        if self.annotation_level is None and "annotation_level" in self.model_fields_set:
            _dict['annotation_level'] = None

        # set to None if end_column (nullable) is None
        # and model_fields_set contains the field
        if self.end_column is None and "end_column" in self.model_fields_set:
            _dict['end_column'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if raw_details (nullable) is None
        # and model_fields_set contains the field
        if self.raw_details is None and "raw_details" in self.model_fields_set:
            _dict['raw_details'] = None

        # set to None if start_column (nullable) is None
        # and model_fields_set contains the field
        if self.start_column is None and "start_column" in self.model_fields_set:
            _dict['start_column'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckAnnotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annotation_level": obj.get("annotation_level"),
            "blob_href": obj.get("blob_href"),
            "end_column": obj.get("end_column"),
            "end_line": obj.get("end_line"),
            "message": obj.get("message"),
            "path": obj.get("path"),
            "raw_details": obj.get("raw_details"),
            "start_column": obj.get("start_column"),
            "start_line": obj.get("start_line"),
            "title": obj.get("title")
        })
        return _obj


