/*
 * Amazon ElastiCache
 * <fullname>Amazon ElastiCache</fullname> <p>Amazon ElastiCache is a web service that makes it easier to set up, operate, and scale a distributed cache in the cloud.</p> <p>With ElastiCache, customers get all of the benefits of a high-performance, in-memory cache with less of the administrative burden involved in launching and managing a distributed cache. The service makes setup, scaling, and cluster failure handling much simpler than in a self-managed cache deployment.</p> <p>In addition, through integration with Amazon CloudWatch, customers get enhanced visibility into the key performance statistics associated with their cache and can receive alarms if a part of their cache runs hot.</p>
 *
 * The version of the OpenAPI document: 2015-02-02
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.UserGroupPendingChanges;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserGroup
 */
public class UserGroupTest {
    private final UserGroup model = new UserGroup();

    /**
     * Model tests for UserGroup
     */
    @Test
    public void testUserGroup() {
        // TODO: test UserGroup
    }

    /**
     * Test the property 'userGroupId'
     */
    @Test
    public void userGroupIdTest() {
        // TODO: test userGroupId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'engine'
     */
    @Test
    public void engineTest() {
        // TODO: test engine
    }

    /**
     * Test the property 'userIds'
     */
    @Test
    public void userIdsTest() {
        // TODO: test userIds
    }

    /**
     * Test the property 'minimumEngineVersion'
     */
    @Test
    public void minimumEngineVersionTest() {
        // TODO: test minimumEngineVersion
    }

    /**
     * Test the property 'pendingChanges'
     */
    @Test
    public void pendingChangesTest() {
        // TODO: test pendingChanges
    }

    /**
     * Test the property 'replicationGroups'
     */
    @Test
    public void replicationGroupsTest() {
        // TODO: test replicationGroups
    }

    /**
     * Test the property 'ARN'
     */
    @Test
    public void ARNTest() {
        // TODO: test ARN
    }

}
