# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vc3_scan_type_conversion_mode import Vc3ScanTypeConversionMode

class TestVc3ScanTypeConversionMode(unittest.TestCase):
    """Vc3ScanTypeConversionMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVc3ScanTypeConversionMode(self):
        """Test Vc3ScanTypeConversionMode"""
        # inst = Vc3ScanTypeConversionMode()

if __name__ == '__main__':
    unittest.main()
