# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.embedded_convert608_to708 import EmbeddedConvert608To708

class TestEmbeddedConvert608To708(unittest.TestCase):
    """EmbeddedConvert608To708 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbeddedConvert608To708(self):
        """Test EmbeddedConvert608To708"""
        # inst = EmbeddedConvert608To708()

if __name__ == '__main__':
    unittest.main()
