# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.mpeg2_quality_tuning_level import Mpeg2QualityTuningLevel

class TestMpeg2QualityTuningLevel(unittest.TestCase):
    """Mpeg2QualityTuningLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMpeg2QualityTuningLevel(self):
        """Test Mpeg2QualityTuningLevel"""
        # inst = Mpeg2QualityTuningLevel()

if __name__ == '__main__':
    unittest.main()
