# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hls_initialization_vector_in_manifest import HlsInitializationVectorInManifest

class TestHlsInitializationVectorInManifest(unittest.TestCase):
    """HlsInitializationVectorInManifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHlsInitializationVectorInManifest(self):
        """Test HlsInitializationVectorInManifest"""
        # inst = HlsInitializationVectorInManifest()

if __name__ == '__main__':
    unittest.main()
