/*
 * Google Vault API
 * Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HangoutsChatOptions
 */
public class HangoutsChatOptionsTest {
    private final HangoutsChatOptions model = new HangoutsChatOptions();

    /**
     * Model tests for HangoutsChatOptions
     */
    @Test
    public void testHangoutsChatOptions() {
        // TODO: test HangoutsChatOptions
    }

    /**
     * Test the property 'includeRooms'
     */
    @Test
    public void includeRoomsTest() {
        // TODO: test includeRooms
    }

}
