# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.org_pre_receive_hook import OrgPreReceiveHook

class TestOrgPreReceiveHook(unittest.TestCase):
    """OrgPreReceiveHook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgPreReceiveHook:
        """Test OrgPreReceiveHook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgPreReceiveHook`
        """
        model = OrgPreReceiveHook()
        if include_optional:
            return OrgPreReceiveHook(
                allow_downstream_configuration = True,
                configuration_url = '',
                enforcement = '',
                id = 56,
                name = ''
            )
        else:
            return OrgPreReceiveHook(
        )
        """

    def testOrgPreReceiveHook(self):
        """Test OrgPreReceiveHook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
