# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.mpeg2_interlace_mode import Mpeg2InterlaceMode

class TestMpeg2InterlaceMode(unittest.TestCase):
    """Mpeg2InterlaceMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMpeg2InterlaceMode(self):
        """Test Mpeg2InterlaceMode"""
        # inst = Mpeg2InterlaceMode()

if __name__ == '__main__':
    unittest.main()
