# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.caption_destination_settings_burnin_destination_settings import CaptionDestinationSettingsBurninDestinationSettings

class TestCaptionDestinationSettingsBurninDestinationSettings(unittest.TestCase):
    """CaptionDestinationSettingsBurninDestinationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaptionDestinationSettingsBurninDestinationSettings:
        """Test CaptionDestinationSettingsBurninDestinationSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaptionDestinationSettingsBurninDestinationSettings`
        """
        model = CaptionDestinationSettingsBurninDestinationSettings()
        if include_optional:
            return CaptionDestinationSettingsBurninDestinationSettings(
                alignment = None,
                apply_font_color = None,
                background_color = None,
                background_opacity = None,
                fallback_font = None,
                font_color = None,
                font_opacity = None,
                font_resolution = None,
                font_script = None,
                font_size = None,
                hex_font_color = None,
                outline_color = None,
                outline_size = None,
                shadow_color = None,
                shadow_opacity = None,
                shadow_x_offset = None,
                shadow_y_offset = None,
                style_passthrough = None,
                teletext_spacing = None,
                x_position = None,
                y_position = None
            )
        else:
            return CaptionDestinationSettingsBurninDestinationSettings(
        )
        """

    def testCaptionDestinationSettingsBurninDestinationSettings(self):
        """Test CaptionDestinationSettingsBurninDestinationSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
