# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vp8_par_control import Vp8ParControl

class TestVp8ParControl(unittest.TestCase):
    """Vp8ParControl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVp8ParControl(self):
        """Test Vp8ParControl"""
        # inst = Vp8ParControl()

if __name__ == '__main__':
    unittest.main()
