# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cmaf_write_segment_timeline_in_representation import CmafWriteSegmentTimelineInRepresentation

class TestCmafWriteSegmentTimelineInRepresentation(unittest.TestCase):
    """CmafWriteSegmentTimelineInRepresentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCmafWriteSegmentTimelineInRepresentation(self):
        """Test CmafWriteSegmentTimelineInRepresentation"""
        # inst = CmafWriteSegmentTimelineInRepresentation()

if __name__ == '__main__':
    unittest.main()
