# coding: utf-8

"""
    AWS Elemental MediaConvert

    AWS Elemental MediaConvert

    The version of the OpenAPI document: 2017-08-29
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.mpeg2_scene_change_detect import Mpeg2SceneChangeDetect

class TestMpeg2SceneChangeDetect(unittest.TestCase):
    """Mpeg2SceneChangeDetect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMpeg2SceneChangeDetect(self):
        """Test Mpeg2SceneChangeDetect"""
        # inst = Mpeg2SceneChangeDetect()

if __name__ == '__main__':
    unittest.main()
