# coding: utf-8

"""
    Message Center API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model401_unauthorized import Model401Unauthorized

class TestModel401Unauthorized(unittest.TestCase):
    """Model401Unauthorized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model401Unauthorized:
        """Test Model401Unauthorized
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model401Unauthorized`
        """
        model = Model401Unauthorized()
        if include_optional:
            return Model401Unauthorized(
                status = 401,
                title = 'Unauthorized',
                trace_id = '00-bf325375e030fccba00917317c574773-100bf03b5fc61486-00',
                type = 'https://tools.ietf.org/html/rfc7235#section-3.1'
            )
        else:
            return Model401Unauthorized(
                status = 401,
                title = 'Unauthorized',
                trace_id = '00-bf325375e030fccba00917317c574773-100bf03b5fc61486-00',
                type = 'https://tools.ietf.org/html/rfc7235#section-3.1',
        )
        """

    def testModel401Unauthorized(self):
        """Test Model401Unauthorized"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
