# coding: utf-8

"""
    AWS IoT Wireless

    <p>AWS IoT Wireless provides bi-directional communication between internet-connected wireless devices and the AWS Cloud. To onboard both LoRaWAN and Sidewalk devices to AWS IoT, use the IoT Wireless API. These wireless devices use the Low Power Wide Area Networking (LPWAN) communication protocol to communicate with AWS IoT.</p> <p>Using the API, you can perform create, read, update, and delete operations for your wireless devices, gateways, destinations, and profiles. After onboarding your devices, you can use the API operations to set log levels and monitor your devices with CloudWatch.</p> <p>You can also use the API operations to create multicast groups and schedule a multicast session for sending a downlink message to devices in the group. By using Firmware Updates Over-The-Air (FUOTA) API operations, you can create a FUOTA task and schedule a session to update the firmware of individual devices or an entire group of devices in a multicast group.</p>

    The version of the OpenAPI document: 2020-11-22
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LoRaWANDeviceProfile(BaseModel):
    """
    LoRaWANDeviceProfile object.
    """ # noqa: E501
    supports_class_b: Optional[Any] = Field(default=None, alias="SupportsClassB")
    class_b_timeout: Optional[Any] = Field(default=None, alias="ClassBTimeout")
    ping_slot_period: Optional[Any] = Field(default=None, alias="PingSlotPeriod")
    ping_slot_dr: Optional[Any] = Field(default=None, alias="PingSlotDr")
    ping_slot_freq: Optional[Any] = Field(default=None, alias="PingSlotFreq")
    supports_class_c: Optional[Any] = Field(default=None, alias="SupportsClassC")
    class_c_timeout: Optional[Any] = Field(default=None, alias="ClassCTimeout")
    mac_version: Optional[Any] = Field(default=None, alias="MacVersion")
    reg_params_revision: Optional[Any] = Field(default=None, alias="RegParamsRevision")
    rx_delay1: Optional[Any] = Field(default=None, alias="RxDelay1")
    rx_dr_offset1: Optional[Any] = Field(default=None, alias="RxDrOffset1")
    rx_data_rate2: Optional[Any] = Field(default=None, alias="RxDataRate2")
    rx_freq2: Optional[Any] = Field(default=None, alias="RxFreq2")
    factory_preset_freqs_list: Optional[Any] = Field(default=None, alias="FactoryPresetFreqsList")
    max_eirp: Optional[Any] = Field(default=None, alias="MaxEirp")
    max_duty_cycle: Optional[Any] = Field(default=None, alias="MaxDutyCycle")
    rf_region: Optional[Any] = Field(default=None, alias="RfRegion")
    supports_join: Optional[Any] = Field(default=None, alias="SupportsJoin")
    supports32_bit_f_cnt: Optional[Any] = Field(default=None, alias="Supports32BitFCnt")
    __properties: ClassVar[List[str]] = ["SupportsClassB", "ClassBTimeout", "PingSlotPeriod", "PingSlotDr", "PingSlotFreq", "SupportsClassC", "ClassCTimeout", "MacVersion", "RegParamsRevision", "RxDelay1", "RxDrOffset1", "RxDataRate2", "RxFreq2", "FactoryPresetFreqsList", "MaxEirp", "MaxDutyCycle", "RfRegion", "SupportsJoin", "Supports32BitFCnt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoRaWANDeviceProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoRaWANDeviceProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "SupportsClassB": obj.get("SupportsClassB"),
            "ClassBTimeout": obj.get("ClassBTimeout"),
            "PingSlotPeriod": obj.get("PingSlotPeriod"),
            "PingSlotDr": obj.get("PingSlotDr"),
            "PingSlotFreq": obj.get("PingSlotFreq"),
            "SupportsClassC": obj.get("SupportsClassC"),
            "ClassCTimeout": obj.get("ClassCTimeout"),
            "MacVersion": obj.get("MacVersion"),
            "RegParamsRevision": obj.get("RegParamsRevision"),
            "RxDelay1": obj.get("RxDelay1"),
            "RxDrOffset1": obj.get("RxDrOffset1"),
            "RxDataRate2": obj.get("RxDataRate2"),
            "RxFreq2": obj.get("RxFreq2"),
            "FactoryPresetFreqsList": obj.get("FactoryPresetFreqsList"),
            "MaxEirp": obj.get("MaxEirp"),
            "MaxDutyCycle": obj.get("MaxDutyCycle"),
            "RfRegion": obj.get("RfRegion"),
            "SupportsJoin": obj.get("SupportsJoin"),
            "Supports32BitFCnt": obj.get("Supports32BitFCnt")
        })
        return _obj


