# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.enterprise_admin_delete_pre_receive_environment422_response import EnterpriseAdminDeletePreReceiveEnvironment422Response

class TestEnterpriseAdminDeletePreReceiveEnvironment422Response(unittest.TestCase):
    """EnterpriseAdminDeletePreReceiveEnvironment422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnterpriseAdminDeletePreReceiveEnvironment422Response:
        """Test EnterpriseAdminDeletePreReceiveEnvironment422Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnterpriseAdminDeletePreReceiveEnvironment422Response`
        """
        model = EnterpriseAdminDeletePreReceiveEnvironment422Response()
        if include_optional:
            return EnterpriseAdminDeletePreReceiveEnvironment422Response(
                errors = [
                    openapi_client.models.enterprise_admin_delete_pre_receive_environment_422_response_errors_inner.enterprise_admin_delete_pre_receive_environment_422_response_errors_inner(
                        code = '', 
                        message = '', 
                        resource = '', )
                    ],
                message = ''
            )
        else:
            return EnterpriseAdminDeletePreReceiveEnvironment422Response(
        )
        """

    def testEnterpriseAdminDeletePreReceiveEnvironment422Response(self):
        """Test EnterpriseAdminDeletePreReceiveEnvironment422Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
