# coding: utf-8

"""
    eBay Finances API

    This API is used to retrieve seller payouts and monetary transaction details related to those payouts.

    The version of the OpenAPI document: v1.15.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payout import Payout

class TestPayout(unittest.TestCase):
    """Payout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Payout:
        """Test Payout
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Payout`
        """
        model = Payout()
        if include_optional:
            return Payout(
                amount = openapi_client.models.amount.Amount(
                    converted_from_currency = '', 
                    converted_from_value = '', 
                    currency = '', 
                    exchange_rate = '', 
                    value = '', ),
                bank_reference = '',
                last_attempted_payout_date = '',
                payout_date = '',
                payout_id = '',
                payout_instrument = openapi_client.models.payout_instrument.PayoutInstrument(
                    account_last_four_digits = '', 
                    instrument_type = '', 
                    nickname = '', ),
                payout_memo = '',
                payout_status = '',
                payout_status_description = '',
                total_amount = openapi_client.models.amount.Amount(
                    converted_from_currency = '', 
                    converted_from_value = '', 
                    currency = '', 
                    exchange_rate = '', 
                    value = '', ),
                total_fee = openapi_client.models.amount.Amount(
                    converted_from_currency = '', 
                    converted_from_value = '', 
                    currency = '', 
                    exchange_rate = '', 
                    value = '', ),
                transaction_count = 56
            )
        else:
            return Payout(
        )
        """

    def testPayout(self):
        """Test Payout"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
