# coding: utf-8

"""
    Application Migration Service

    The Application Migration Service service.

    The version of the OpenAPI document: 2020-02-26
    Contact: mike.ralphson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.import_task_error import ImportTaskError

class TestImportTaskError(unittest.TestCase):
    """ImportTaskError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportTaskError:
        """Test ImportTaskError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportTaskError`
        """
        model = ImportTaskError()
        if include_optional:
            return ImportTaskError(
                error_data = None,
                error_date_time = None,
                error_type = None
            )
        else:
            return ImportTaskError(
        )
        """

    def testImportTaskError(self):
        """Test ImportTaskError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
