# coding: utf-8

"""
    Twilio - Taskrouter

    This is the public Twilio REST API.

    The version of the OpenAPI document: 1.42.0
    Contact: support@twilio.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_activity_response import ListActivityResponse

class TestListActivityResponse(unittest.TestCase):
    """ListActivityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListActivityResponse:
        """Test ListActivityResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListActivityResponse`
        """
        model = ListActivityResponse()
        if include_optional:
            return ListActivityResponse(
                activities = [
                    openapi_client.models.taskrouter/v1/workspace/activity.taskrouter.v1.workspace.activity(
                        account_sid = 'AC62ECB020842930cc01FFCCfeEe150AC30123456789101112131415161718192021222324252627282930313233', 
                        available = True, 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        friendly_name = '', 
                        links = openapi_client.models.links.links(), 
                        sid = 'WA62ECB020842930cc01FFCCfeEe150AC30123456789101112131415161718192021222324252627282930313233', 
                        url = '', 
                        workspace_sid = 'WS62ECB020842930cc01FFCCfeEe150AC30123456789101112131415161718192021222324252627282930313233', )
                    ],
                meta = openapi_client.models.list_workspace_response_meta.ListWorkspaceResponse_meta(
                    first_page_url = '', 
                    key = '', 
                    next_page_url = '', 
                    page = 56, 
                    page_size = 56, 
                    previous_page_url = '', 
                    url = '', )
            )
        else:
            return ListActivityResponse(
        )
        """

    def testListActivityResponse(self):
        """Test ListActivityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
