# coding: utf-8

"""
    Transport Department, West Bengal

    Driving License (DL) and Vehicle Registration Certificate (RC) of the State, as available on Parivahan Sewa (http://parivahan.co.in/) of Ministry of Road Transport and Highways, are available on DigiLocker. Citizens can pull these documents into their DigiLocker accounts.

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vehicle_registration_schema_certificate_data_vehicle_registration_vehicle import VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle

class TestVehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle(unittest.TestCase):
    """VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle:
        """Test VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle`
        """
        model = VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle()
        if include_optional:
            return VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle(
                chasis_no = '0',
                var_class = openapi_client.models.class.class(),
                color = '',
                cubic_capacity = openapi_client.models.cubic_capacity.cubicCapacity(),
                cylinder = openapi_client.models.cylinder.cylinder(),
                engine_no = '',
                fit_till = openapi_client.models.fit_till.fitTill(),
                fuel_desc = openapi_client.models.fuel_desc.fuelDesc(),
                make = openapi_client.models.make.make(),
                mfg_date = openapi_client.models.mfg_date.mfgDate(),
                model = '0',
                seat_capacity = '0',
                sleeper_capacity = '0',
                standing_capacity = openapi_client.models.standing_capacity.standingCapacity(),
                unladen_weight = '0',
                wheelbase = openapi_client.models.wheelbase.wheelbase()
            )
        else:
            return VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle(
        )
        """

    def testVehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle(self):
        """Test VehicleRegistrationSchemaCertificateDataVehicleRegistrationVehicle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
